### ISSUE TITLE
Stuck on Loading... screen

### ISSUE THREAD

**Issue by dylib** [macmade/Console#1]
Is there some secret trick to seeing more than only the "Loading..." screen?
![loading...](https://cloud.githubusercontent.com/assets/17288131/26566258/a09b3d1c-44a6-11e7-9fbf-045caf842637.png)
I waited a good hour on that screen before deciding to reach out and post this...

**Comment by macmade** [comment]
Looks like there's an issue getting messages from ASL.
Which macOS version are you using?

**Comment by dylib** [comment]
I'm using 10.12.5 (16F73)

**Comment by dylib** [comment]
Ah well, it was worth a try at least... guess this one is dead. ☠️

**Comment by macmade** [comment]
Well, not really, but maybe you could try to help providing a some more infos, as I cannot reproduce the issue myself.

Have you built the project with Xcode? If so, can you provide some backtrace?

**Comment by dylib** [comment]
It maybe the issue is that the project does not include `../Submodules/SeriousCode/clang-warnings.h` referenced from `Console-Prefix.pch`. When the include/import is commented out the app stays on "Loading Messages..." the entire time.

So I guess the question becomes where do I get the header file `clang-warnings.h`?

**Comment by macmade** [comment]
It comes from a Git submodule.
So just clone and checkout the submodules...

**Comment by dylib** [comment]
I added the submodule, and now when I try to build there's a few errors:
```
PreferencesWindowController.m:169:38: Implicit conversion from nullable pointer 'NSString * _Nullable' to non-nullable pointer type 'NSString * _Nonnull'

MainWindowController.m:221:35: Implicit conversion from nullable pointer 'NSString * _Nullable' to non-nullable pointer type 'NSString * _Nonnull'

Preferences.m:76:114: Implicit conversion from nullable pointer 'NSString * _Nullable' to non-nullable pointer type 'NSString * _Nonnull'
```
Deployment Target: `10.11`, `Xcode Version 8.3.3 (8E3004b)`,  SDK: `Latest macOS 10.12`

**Comment by macmade** [comment]
Weird I don't get the same errors...

But should be fixed in 202db064aa94d81a922a029a58291592bc1abda3.

**Comment by dylib** [comment]
Thanks for taking a look into the issue; I still get a few additional errors as mentioned above. I was able to fix the others by doing this for example:

**Error**:
```
Implicit conversion from nullable pointer 'NSString * _Nullable' to non-nullable pointer type 'NSString * _Nonnull'
```

**Original**:
```
defaults = [ NSDictionary dictionaryWithContentsOfFile: [ [ NSBundle mainBundle ] pathForResource: @"Defaults" ofType: @"plist" ] ];
```

**Change**:
```
NSString *filePath = [[ NSBundle mainBundle ] pathForResource: @"Defaults" ofType: @"plist" ] ;
defaults = [ NSDictionary dictionaryWithContentsOfFile: filePath ];
```
It builds after making the changes ( no idea why it doesn't like the syntax of the original ). Unfortunately it still only displays the `Loading...` screen.  I'm sort of at a loss as to what to look for since the app isn't crashing or anything like that — actually I'm quite perplexed about it.

In the native Console.app I notice these messages ( which might just be related to the native Console.app, but just in case ).:
```
2017-07-26 00:43:36.385284 -0700	27935	Console	compiling shader
2017-07-26 00:43:36.399515 -0700	27935	Console	compiling shader
2017-07-26 00:43:36.517558 -0700	27935	Console	Loading Preferences From User CFPrefsD
2017-07-26 00:43:36.688598 -0700	27935	Console	_CopyData
2017-07-26 00:43:36.689738 -0700	27935	Console	_CopyData
2017-07-26 00:43:36.690261 -0700	27935	Console	_CopyData
2017-07-26 00:43:36.690801 -0700	27935	Console	Loading Preferences From System CFPrefsD For Search List
2017-07-26 00:43:36.690856 -0700	27935	Console	Loading Preferences From User CFPrefsD For Search List
2017-07-26 00:44:04.325839 -0700	27935	Console	trackMouse send action on mouseUp
2017-07-26 00:44:04.325877 -0700	27935	Console	sendActionFrom:
2017-07-26 00:44:04.325944 -0700	27935	Console	sendAction:
2017-07-26 00:44:19.119546 -0700	27935	Console	trackMouse send action on mouseUp
2017-07-26 00:44:19.119580 -0700	27935	Console	sendActionFrom:
2017-07-26 00:44:19.119617 -0700	27935	Console	sendAction:
2017-07-26 00:44:44.568238 -0700	27935	Console	GetDataFlags
2017-07-26 00:44:44.568342 -0700	27935	Console	_CopyData
2017-07-26 00:44:44.571748 -0700	27935	Console	performKeyEquivalent:
2017-07-26 00:44:44.572835 -0700	27935	Console	sendAction:
2017-07-26 00:44:49.045678 -0700	27935	Console	Loading Preferences From User CFPrefsD
2017-07-26 00:44:55.253259 -0700	27935	Console	performKeyEquivalent:
2017-07-26 00:44:55.254285 -0700	27935	Console	sendAction:
2017-07-26 00:44:56.031264 -0700	27935	Console	trackMouse send action on mouseUp
2017-07-26 00:44:56.031301 -0700	27935	Console	sendActionFrom:
2017-07-26 00:44:56.031350 -0700	27935	Console	sendAction:
2017-07-26 00:45:00.439585 -0700	27935	Console	performKeyEquivalent:
2017-07-26 00:45:00.440572 -0700	27935	Console	sendAction:
2017-07-26 00:45:01.923895 -0700	27935	Console	performKeyEquivalent:
2017-07-26 00:44:44.572835 -0700	27935	Console	sendAction:
```
Anyway... :/

**Comment by dylib** [comment]
Hey good news! The app finally builds and runs as expected. I'm not sure what the exact cause of the issue was to be honest. I think maybe there was something within the OS or Xcode that might've caused the problem, but again I have no idea as the issue just seemed to magically go away (maybe after updating either of the two at some point).

The standard **Console.app** is absolutely awful, so your app is definitely a blessing. Thank you for making it available — best regards and cheers!
